-- MySQL Script generated by MySQL Workbench
-- Sat Jul 12 05:09:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema steminedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema steminedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `steminedb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `steminedb` ;

-- -----------------------------------------------------
-- Table `steminedb`.`community_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steminedb`.`community_posts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(255) NULL DEFAULT NULL,
  `comments_count` BIGINT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `event_date` DATE NULL DEFAULT NULL,
  `event_link` VARCHAR(255) NULL DEFAULT NULL,
  `event_location` TEXT NULL DEFAULT NULL,
  `event_time` VARCHAR(255) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `post_type` ENUM('ARTICLE', 'EVENT') NOT NULL,
  `posted_date` DATE NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `votes` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `steminedb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steminedb`.`courses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categories` TEXT NULL DEFAULT NULL,
  `company_logo_url` VARCHAR(255) NULL DEFAULT NULL,
  `course_url` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `duration_unit` VARCHAR(255) NULL DEFAULT NULL,
  `duration_value` VARCHAR(255) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `level` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `steminedb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steminedb`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `steminedb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steminedb`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `profile_photo_url` VARCHAR(255) NULL DEFAULT NULL,
  `area_of_interest` VARCHAR(255) NULL DEFAULT NULL,
  `experience_level` VARCHAR(255) NULL DEFAULT NULL,
  `purpose_of_mentoring` TEXT NULL DEFAULT NULL,
  `biography` TEXT NULL DEFAULT NULL,
  `has_disability` TINYINT(1) NULL DEFAULT NULL,
  `disability_type` VARCHAR(255) NULL DEFAULT NULL,
  `adaptation_needed` TEXT NULL DEFAULT NULL,
  `linkedin_url` VARCHAR(255) NULL DEFAULT NULL,
  `portfolio_url` VARCHAR(255) NULL DEFAULT NULL,
  `github_url` VARCHAR(255) NULL DEFAULT NULL,
  `lattes_url` VARCHAR(255) NULL DEFAULT NULL,
  `current_challenges` TEXT NULL DEFAULT NULL,
  `curriculum_file_url` VARCHAR(255) NULL DEFAULT NULL,
  `time_availability` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `steminedb`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steminedb`.`user_roles` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `user_roles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `steminedb`.`users` (`id`),
  CONSTRAINT `user_roles_ibfk_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `steminedb`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `steminedb`.`vacancies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steminedb`.`vacancies` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `application_link` VARCHAR(255) NULL DEFAULT NULL,
  `benefits` TEXT NULL DEFAULT NULL,
  `company` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `level` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `posted_date` DATE NULL DEFAULT NULL,
  `requirements` TEXT NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT IGNORE INTO roles (name) VALUES ('ROLE_USER');
INSERT IGNORE INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT IGNORE INTO roles (name) VALUES ('ROLE_MENTOR'); 

-- Opcional: Verifique se as roles foram inseridas
SELECT * FROM roles;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
